test:
  adapter: mysql
  database: kv_test
  username: root
  password: <%= ENV['MYSQLKV_PASSWORD'] %>
  host: localhost
development:
  adapter: mysql
  database: kv_development
  username: root
  password: <%= ENV['MYSQLKV_PASSWORD'] %>
  host: localhost
production:
  adapter: mysql
  database: kv_production
  username: root
  password: <%= ENV['MYSQLKV_PASSWORD'] %>
  host: localhost
